Repository wecode-bootcamp-korea/37-1st-Just-Do-It-backend, pull requests merged in 2022-09, with the labels that each got.

#2 initial-setting
  .env.sample
  .gitignore
  apis/controllers/index.js
  apis/controllers/userController.js
  apis/models/dataSource.js
  apis/models/index.js
  apis/models/userDao.js
  apis/routes/index.js
  apis/routes/userRouter.js
  apis/services/index.js
  apis/services/userService.js
  app.js
  package-lock.json
  package.json
Labels: 완료

#3 add db migrations
  db/migrations/20220920085829_create_brands_table.sql
  db/migrations/20220920090328_create_products_table.sql
  db/migrations/20220920091019_create_product_images_table.sql
  db/migrations/20220920091323_create_colors_table.sql
  db/migrations/20220920091425_create_sizes_table.sql
  db/migrations/20220920091851_create_product_options_table.sql
  db/migrations/20220920092410_create_promotions_table.sql
  db/migrations/20220920092922_create_users_table.sql
  db/migrations/20220920093344_create_promotions_users_table.sql
  db/migrations/20220920093631_create_carts_table.sql
  db/migrations/20220920094414_create_reviews_table.sql
  db/migrations/20220920094642_create_wishlist_table.sql
Labels: 완료

#4 Feature/add db migrations
  db/migrations/20220920090328_create_products_table.sql
Labels: 완료

#5 [ADD] feature/signin
  apis/controllers/index.js
  apis/controllers/userController.js
  apis/models/dataSource.js
  apis/models/index.js
  apis/models/userDao.js
  apis/routes/index.js
  apis/routes/userRouter.js
  apis/services/index.js
  apis/services/userService.js
  apis/utils/error.js
  app.js
  package-lock.json
  package.json
  pull_request_template.md
Labels: 멘토 리뷰 요청

#10 [MODIFY]signin
  apis/controllers/userController.js
  apis/models/userDao.js
  apis/services/userService.js
Labels: 완료

#8 [MODIFY] Feature/signup
  apis/controllers/userController.js
  apis/models/dataSource.js
  apis/models/index.js
  apis/models/userDao.js
  apis/routes/index.js
  apis/routes/userRouter.js
  apis/services/userService.js
  apis/utils/auth.js
  apis/utils/error.js
Labels: 완료

#13 [ADD] feature/product list
  apis/controllers/index.js
  apis/controllers/productController.js
  apis/models/index.js
  apis/models/productDao.js
  apis/routes/index.js
  apis/routes/productRouter.js
  apis/services/index.js
  apis/services/productService.js
Labels: 완료

#15 [ADD] feature/get-detail-in-cart
  apis/controllers/cartController.js
  apis/models/cartDao.js
  apis/models/dataSource.js
  apis/routes/cartRouter.js
  apis/services/cartService.js
  package-lock.json
  package.json
Labels: 완료

#12 [ADD] feature/order
  apis/controllers/index.js
  apis/controllers/orderController.js
  apis/models/cartDao.js
  apis/models/index.js
  apis/models/orderDao.js
  apis/routes/index.js
  apis/routes/orderRouter.js
  apis/services/index.js
  apis/services/orderService.js
Labels: 완료

#14 [ADD] Feature/detail
  apis/controllers/productController.js
  apis/models/productDao.js
  apis/services/productService.js
  apis/utils/auth.js
  package-lock.json
  package.json
Labels: Conflict 해결 요청
